# Generated by Django 5.1.6 on 2025-02-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_customuser_alter_regmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.regmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
