# Generated by Django 5.1.6 on 2025-02-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_taskmodel_user_alter_taskmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.regmodel'),
        ),
    ]
