# Generated by Django 5.1.6 on 2025-02-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_taskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.regmodel'),
        ),
    ]
