# Generated by Django 5.1.6 on 2025-02-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_taskmodel_user_id_taskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='regmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.regmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Other', 'Other')], max_length=50),
        ),
    ]
