# Generated by Django 5.1.6 on 2025-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_taskmodel_id_taskmodel_regmodel_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='regmodel_ptr',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
